apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-env-config
data:
  Uragsha_TestEnvValue: This value is from K8s!
  Uragsha_Url__Signalling: https://signalling.uragsha.com
  Uragsha_Url__WebApi: https://webapi.uragsha.com


    