apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deployment
  labels:
    app: {{ .Values.uragsha.apps.scheduler.name }}
spec:
  replicas: {{ .Values.uragsha.apps.scheduler.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.uragsha.apps.scheduler.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.uragsha.apps.scheduler.name }}
    spec:
      containers:
        - name: {{ .Values.uragsha.apps.scheduler.name }}
          image: {{ .Values.uragsha.apps.scheduler.image }}
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: backend-env-config
            - secretRef:
                name: backend-env-config-secret


