apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: {{ .Values.uragsha.apps.webapp.name }}
spec:
  replicas: {{ .Values.uragsha.apps.webapp.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.uragsha.apps.webapp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.uragsha.apps.webapp.name }}
    spec:
      containers:
      - name: {{ .Values.uragsha.apps.webapp.name }}
        image: "{{ .Values.uragsha.apps.webapp.image }}:{{ .Values.appVersion}}"
        ports:
        - containerPort: 80
