apiVersion: apps/v1
kind: Deployment
metadata:
  name: signalling-deployment
  labels:
    app: {{ .Values.uragsha.apps.signalling.name }}
spec:
  replicas: {{ .Values.uragsha.apps.signalling.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.uragsha.apps.signalling.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.uragsha.apps.signalling.name }}
    spec:
      containers:
        - name: {{ .Values.uragsha.apps.signalling.name }}
          image: "{{ .Values.uragsha.apps.signalling.image }}:{{ .Values.appVersion}}"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: backend-env-config
            - secretRef:
                name: backend-env-config-secret
