# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: uragsha_local
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
    
  # web:
  #   image: php:7.2.2-apache
  #   container_name: php_web
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./php/:/var/www/html/
  #   ports:
  #     - "8100:80"
  #   stdin_open: true
  #   tty: true