name: Deploy Webapp project to Firebase Webapp on push
'on':
  push:
    branches:
      - main
    paths:
      - 'webapp/**'
      - '!webapp/functions/**'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: webapp-cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: npm intall
        run: npm install
        working-directory: webapp

      - name: npm run build
        run: npm run build
        working-directory: webapp
        
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_URAGSHA_WEBAPP }}'
          channelId: live
          projectId: uragsha-webapp
          entryPoint: webapp