name: Build and deploy Webapp project to Firebase Webapp on push
'on':
  push:
    branches:
      - main
    path:
      - 'webapp'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build webapp
        working-directory: webapp
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_URAGSHA_WEBAPP }}'
          channelId: live
          projectId: uragsha-webapp